/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:801453:
  println("textarea1 - GTextArea event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:textarea1:801453:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:textfield3:985737:
  println("textfield3 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:textfield3:985737:

public void humedadS_change1(GTextField source, GEvent event) { //_CODE_:humedadS:244801:
  println("textfield1 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:humedadS:244801:

public void tempS_change1(GTextField source, GEvent event) { //_CODE_:tempS:724226:
  println("textfield2 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:tempS:724226:

public void tempA_change1(GTextField source, GEvent event) { //_CODE_:tempA:972846:
  println("textfield4 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:tempA:972846:

public void humedadA_change1(GTextField source, GEvent event) { //_CODE_:humedadA:794090:
  println("textfield5 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:humedadA:794090:

public void Luz_change1(GTextField source, GEvent event) { //_CODE_:Luz:944592:
  println("textfield6 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:Luz:944592:

public void velViento_change1(GTextField source, GEvent event) { //_CODE_:velViento:564941:
  println("textfield7 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:velViento:564941:

public void dirViento_change1(GTextField source, GEvent event) { //_CODE_:dirViento:947670:
  println("textfield8 - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:dirViento:947670:


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(HAND);
  if(frame != null)
    frame.setTitle("Sketch Window");
  boton_serial = new GButton(this, 601, 430, 110, 44);
  boton_serial.setText("Conectar Serial");
  boton_serial.setTextBold();
  boton_serial.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  boton_serial.addEventHandler(this, "boton_serial_click");
  label1 = new GLabel(this, 117, 89, 151, 20);
  label1.setText("Humedad del Suelo");
  label1.setTextBold();
  label1.setOpaque(true);
  label2 = new GLabel(this, 118, 129, 151, 21);
  label2.setText("Temperatura del Suelo");
  label2.setTextBold();
  label2.setOpaque(true);
  label3 = new GLabel(this, 118, 167, 150, 21);
  label3.setText("Temperatura del Aire");
  label3.setTextBold();
  label3.setOpaque(true);
  label4 = new GLabel(this, 118, 209, 149, 19);
  label4.setText("Humedad del Aire");
  label4.setTextBold();
  label4.setOpaque(true);
  label5 = new GLabel(this, 119, 249, 149, 20);
  label5.setText("Luminosidad");
  label5.setTextBold();
  label5.setOpaque(true);
  label6 = new GLabel(this, 118, 289, 149, 20);
  label6.setText("Velocidad del Viento");
  label6.setTextBold();
  label6.setOpaque(true);
  label7 = new GLabel(this, 119, 329, 149, 20);
  label7.setText("Dirección del Viento");
  label7.setTextBold();
  label7.setOpaque(true);
  humedadS = new GTextField(this, 310, 88, 108, 21, G4P.SCROLLBARS_NONE);
  humedadS.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  humedadS.setOpaque(true);
  humedadS.addEventHandler(this, "humedadS_change1");
  tempS = new GTextField(this, 310, 129, 108, 20, G4P.SCROLLBARS_NONE);
  tempS.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  tempS.setOpaque(true);
  tempS.addEventHandler(this, "tempS_change1");
  label8 = new GLabel(this, 384, 431, 126, 34);
  label8.setText("Elegir número de Puerto Serial");
  label8.setTextBold();
  label8.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label8.setOpaque(true);
  togGroup1 = new GToggleGroup();
  togGroup2 = new GToggleGroup();
  togGroup3 = new GToggleGroup();
  togGroup4 = new GToggleGroup();
  togGroup5 = new GToggleGroup();
  togGroup6 = new GToggleGroup();
  textarea1 = new GTextArea(this, 210, 459, 66, 133, G4P.SCROLLBARS_NONE);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  label9 = new GLabel(this, 194, 416, 91, 33);
  label9.setText("Puertos Disponibles");
  label9.setTextBold();
  label9.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label9.setOpaque(true);
  textfield3 = new GTextField(this, 422, 484, 52, 30, G4P.SCROLLBARS_NONE);
  textfield3.setOpaque(true);
  textfield3.addEventHandler(this, "textfield3_change1");
  label10 = new GLabel(this, 591, 485, 133, 61);
  label10.setText("Sin Conexión");
  label10.setTextBold();
  label10.setLocalColorScheme(GCScheme.RED_SCHEME);
  label10.setOpaque(true);
  refresh1 = new GImageButton(this, 433, 83, 30, 30, new String[] { "refresh (1).png", "refresh (2) .png", "refresh (1).png" } );
  refresh1.addEventHandler(this, "refresh1_click");
  refresh2 = new GImageButton(this, 433, 124, 27, 28, new String[] { "refresh (1).png", "refresh (2) .png", "refresh (1).png" } );
  refresh2.addEventHandler(this, "refresh2_click");
  refresh6 = new GImageButton(this, 433, 283, 28, 30, new String[] { "refresh (1).png", "refresh (2) .png", "refresh (1).png" } );
  refresh6.addEventHandler(this, "refresh6_click");
  refresh4 = new GImageButton(this, 431, 204, 33, 30, new String[] { "refresh (1).png", "refresh (2) .png", "refresh (1).png" } );
  refresh4.addEventHandler(this, "refresh4_click");
  refresh3 = new GImageButton(this, 431, 165, 31, 28, new String[] { "refresh (1).png", "refresh (2) .png", "refresh (1).png" } );
  refresh3.addEventHandler(this, "refresh3_click");
  refresh5 = new GImageButton(this, 433, 243, 33, 29, new String[] { "refresh (1).png", "refresh (2) .png", "refresh (1).png" } );
  refresh5.addEventHandler(this, "refresh5_click");
  tempA = new GTextField(this, 308, 168, 110, 21, G4P.SCROLLBARS_NONE);
  tempA.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  tempA.setOpaque(true);
  tempA.addEventHandler(this, "tempA_change1");
  humedadA = new GTextField(this, 307, 208, 111, 21, G4P.SCROLLBARS_NONE);
  humedadA.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  humedadA.setOpaque(true);
  humedadA.addEventHandler(this, "humedadA_change1");
  Luz = new GTextField(this, 309, 249, 109, 21, G4P.SCROLLBARS_NONE);
  Luz.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Luz.setOpaque(true);
  Luz.addEventHandler(this, "Luz_change1");
  velViento = new GTextField(this, 308, 289, 111, 20, G4P.SCROLLBARS_NONE);
  velViento.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  velViento.setOpaque(true);
  velViento.addEventHandler(this, "velViento_change1");
  dirViento = new GTextField(this, 309, 328, 109, 20, G4P.SCROLLBARS_NONE);
  dirViento.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  dirViento.setOpaque(true);
  dirViento.addEventHandler(this, "dirViento_change1");
  refresh17 = new GImageButton(this, 434, 322, 29, 28, new String[] { "refresh (1).png", "refresh (2) .png", "refresh (1).png" } );
  refresh17.addEventHandler(this, "refresh7_click");
  label11 = new GLabel(this, 564, 102, 212, 28);
  label11.setText("Tiempo de espera entre mediciones");
  label11.setTextBold();
  label11.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label11.setOpaque(true);
  enviar_tweets = new GButton(this, 563, 309, 97, 40);
  enviar_tweets.setText("Comenzar envío de tweets");
  enviar_tweets.setTextBold();
  enviar_tweets.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  enviar_tweets.addEventHandler(this, "enviar_tweets_click");
  parar_tweets = new GButton(this, 679, 307, 89, 41);
  parar_tweets.setText("Detener envío de tweets");
  parar_tweets.setTextBold();
  parar_tweets.setLocalColorScheme(GCScheme.RED_SCHEME);
  parar_tweets.addEventHandler(this, "parar_tweets_click");
  Opciones_tiempo = new GToggleGroup();
  option1 = new GOption(this, 619, 149, 120, 20);
  option1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option1.setText("   2 Segundos");
  option1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  option1.setOpaque(false);
  option1.addEventHandler(this, "option1_clicked1");
  option2 = new GOption(this, 619, 170, 120, 20);
  option2.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option2.setText("   5 Segundos");
  option2.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  option2.setOpaque(false);
  option2.addEventHandler(this, "option2_clicked1");
  option3 = new GOption(this, 619, 192, 120, 20);
  option3.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option3.setText("   30 Segundos");
  option3.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  option3.setOpaque(false);
  option3.addEventHandler(this, "option3_clicked1");
  option4 = new GOption(this, 619, 213, 120, 20);
  option4.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option4.setText("   1 Minuto");
  option4.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  option4.setOpaque(false);
  option4.addEventHandler(this, "option4_clicked1");
  option5 = new GOption(this, 619, 235, 120, 20);
  option5.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option5.setText("   5 Minutos");
  option5.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  option5.setOpaque(false);
  option5.addEventHandler(this, "option5_clicked1");
  option6 = new GOption(this, 619, 258, 120, 20);
  option6.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option6.setText("   10 Minutos");
  option6.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  option6.setOpaque(false);
  option6.addEventHandler(this, "option6_clicked1");
  Opciones_tiempo.addControl(option1);
  Opciones_tiempo.addControl(option2);
  //option2.setSelected(true);
  Opciones_tiempo.addControl(option3);
  Opciones_tiempo.addControl(option4);
  Opciones_tiempo.addControl(option5);
  Opciones_tiempo.addControl(option6);
  label12 = new GLabel(this, 262, 5, 399, 30);
  label12.setText("ESTACIÓN METEOROLÓGICA - LABC");
  label12.setTextBold();
  label12.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label12.setOpaque(true);
  label13 = new GLabel(this, 761, 568, 141, 20);
  label13.setText("Danilo Díaz Tarascó");
  label13.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label13.setOpaque(false);
  label14 = new GLabel(this, 753, 587, 160, 20);
  label14.setText("Irene Michelle López C.");
  label14.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  label14.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton boton_serial; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GLabel label7; 
GTextField humedadS; 
GTextField tempS; 
GLabel label8; 
GToggleGroup togGroup1; 
GToggleGroup togGroup2; 
GToggleGroup togGroup3; 
GToggleGroup togGroup4; 
GToggleGroup togGroup5; 
GToggleGroup togGroup6; 
GTextArea textarea1; 
GLabel label9; 
GTextField textfield3; 
GLabel label10; 
GImageButton refresh1; 
GImageButton refresh2; 
GImageButton refresh6; 
GImageButton refresh4; 
GImageButton refresh3; 
GImageButton refresh5; 
GTextField tempA; 
GTextField humedadA; 
GTextField Luz; 
GTextField velViento; 
GTextField dirViento; 
GImageButton refresh17; 
GLabel label11; 
GButton enviar_tweets; 
GButton parar_tweets; 
GToggleGroup Opciones_tiempo; 
GOption option1; 
GOption option2; 
GOption option3; 
GOption option4; 
GOption option5; 
GOption option6; 
GLabel label12; 
GLabel label13; 
GLabel label14;

